version: '3.5'
networks:
  tutorial:
    driver: overlay
    attachable: true
services:
  web:
    image: local/tutorial:latest
    entrypoint: /tutorial/docker-rm-server-pid.sh
    command: ["rails", "s", "-b", "0.0.0.0", "-p", "4000"]
    volumes:
      - .:/tutorial
    ports:
      - '4000:4000'
    env_file: .docker_rails_env
  postgres:
    image: postgres:9.6.3
    volumes:
      - ${SITES}/tutorial/data/pg:/pgdata
    environment:
      POSTGRES_DB: tutorial_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      PGDATA: /pgdata
